### ISSUE TITLE
Feature request: direct download link for latest Joomla version

### ISSUE THREAD

**Issue by pe7er** [joomla/downloads.joomla.org#114]
The Joomla downloads site lists the most recent Joomla release at https://downloads.joomla.org/latest 

It would be nice if you could just use an URL to directly download the latest version, e.g. https://downloads.joomla.org/latest.joomla.zip to download the .zip format of the most recent version.

That way you could always use **wget on the command line to download the latest Joomla version** directly without first having to go to the Joomla downloads website to find (and copy) the full URL to the download.

**Comment by wilsonge** [comment]
There's an API for it already - so this can be done programatically https://downloads.joomla.org/api/v1/latest/cms

**Comment by mbabker** [comment]
You can, but it's still a little tricky to do because you can't build a one-liner for the request.  See https://github.com/joomla/docker-joomla/blob/master/update.php as an example for the work I go through to find the latest version before being able to query the API for specific version information.

**Comment by mbabker** [comment]
If anyone has the copious amounts of free time needed, these types of aliases would need to be added to the routing system (hopefully this is something that could be done through a plugin, otherwise direct editing the ARS router will be required):

- `cms/latest-10.{format}`
- `cms/latest-15.{format}`
- `cms/latest-25.{format}`
- `cms/latest-3.{format}`
- `cms/latest-4.{format}` (when 4.0 stable comes)

I'm hesitant to support a `cms/latest.{format}` alias for the CMS simply because latest is a very vague definition, especially when you have 5 different major version branches (2 of them under active development or support).

For extensions, I think we can get away with a `extensions/{extension-slug}/latest.{format}` URI because we typically aren't going to be supporting two major versions of those at a time (and yes this is me saying we don't need a Weblinks 3.x and 4.x release, it's decoupled so let it follow its own semantic versioning).

**Comment by mbabker** [comment]
https://www.joomla.org/latest has existed for a bit, but it's honestly going to be too opinionated of a resource once 4.0 ships (exactly the concerns I had above).  Either way, that fulfills this request to the extent practical without a full solution like what I suggested before.
